import type { Metadata } from "next";
import { Inter, Bricolage_Grotesque } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Gen/Navbar";
import Footer from "@/components/Gen/Footer";
// import Modal from "@/components/Gen/Modal";

const bricolageGrotesque = Bricolage_Grotesque({
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-bricolage-grotesque",
  subsets: ["latin"],
})

const inter = Inter({ 
  subsets: ["latin"],
  weight : ["100", "200", "300", "400", "500"], 
  variable : "--font-inter" 
});

export const metadata: Metadata = {
  title: "Miss Pepo | Event Host - Actor - Influencer",
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon.ico",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${bricolageGrotesque.className} ${inter.className}`}>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
